modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "matterhorn"
version = "${version}"
displayName = "Matterhorn"
authors = "ebo2022"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.matterhorn]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.matterhorn]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.matterhorn]]
modId="terrablender"
type = "optional"
versionRange="[4.0.0.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "matterhorn-common.mixins.json"
